### ISSUE TITLE
Feature request: Add output coloring, option to disable

### ISSUE THREAD

**Issue by cool-RR** [cool-RR/PySnooper#1]

**Comment by lt94** [comment]
Hey, i'd like to work on this one,any good advice for me?

**Comment by cool-RR** [comment]
Great!

I think this isn't too tricky, just find the color characters for the
shell, and use different colors for different parts of the output. If
there's anything I'd want to correct about your pull request, I'll tell
you.

**Comment by lt94** [comment]
I hava already fix this one,you can see my last commit [#1](https://github.com/cool-RR/PySnooper/compare/master...lt94:master), but got no idea about how to test color. would you mind giving me some help,thx~

**Comment by cool-RR** [comment]
Great, can you submit a pull request to this repo? I tried making sense of your code but couldn't separate your commits from mine on your repo.

**Comment by lt94** [comment]
i made the pr~~O(∩_∩)O

**Comment by cool-RR** [comment]
This PR is up for grabs again. It's a good one, I hope someone takes it.

**Comment by Mark-Jung** [comment]
I'll give it a shot.

**Comment by AtHeartEngineer** [comment]
What about doing this with pycolorama? @Mark-Jung lemme know if you want help, definitely looking forward to this PR.

**Comment by Mark-Jung** [comment]
I haven't looked into this yet, but I will asap. Have been swamped with work this week.

**Comment by alexmojaki** [comment]
Before jumping into a PR with colorama you should be aware that there is a reluctance here to use any dependencies, see #48 and #68

**Comment by cool-RR** [comment]
@AtHeartEngineer : Alex is correct, I prefer to avoid dependencies for this project.

**Comment by alexmojaki** [comment]
> It could be an optional dependency, if you want color

I know @cool-RR is not interested in maintaining optional dependencies either, I tried that too in #71

I tried to make this project extensible in #103 so that another project could be built on top of it with extra features through dependencies, but that's been rejected. I'd already written some code using Pygments which added syntax highlighting in the terminal.

**Comment by cool-RR** [comment]
Anyone reading this: This feature is up for grabs for anyone interested in implementing it.

**Comment by alexmojaki** [comment]
[My version of PySnooper](https://github.com/alexmojaki/snoop) is out and it is colorful! I'd love to hear people's thoughts about the design and use of color [here](https://github.com/alexmojaki/snoop/issues/1).

It seems that colorama is not needed for Windows support after all, which is good because it only supports a few colors anyway. Windows 10 has had support for ANSI codes in cmd for two years now, you just have to enable it: https://stackoverflow.com/a/36760881/2482744 That's what I'm doing. I don't know what happens in other terminals, I'm not a Windows user.

So PySnooper can still accomplish this without dependencies. If you want syntax highlighting, maybe check what https://github.com/Qix-/better-exceptions is doing for ideas.

**Comment by skjerns** [comment]
It would be great to have color coding under windows as well!

`colorama` supports windows, as I have just tested and confirmed :)
