### ISSUE TITLE
How to display this string completely?

### ISSUE THREAD

**Issue by kagxin** [cool-RR/PySnooper#104]
![image](https://user-images.githubusercontent.com/16145883/57423260-d72ef700-7245-11e9-9b10-b8b6b5146afc.png)
How to display this string completely?

**Comment by cool-RR** [comment]
@alexmojaki Why is this string showing so short? When I wrote the code, I made it so it'll truncate at around 100 characters, and when you refactored, you set `self.maxother = 100`. I guess `reprlib.Repr` works differently? In any case I definitely don't want strings to be truncated so much. Can this be fixed?

**Comment by alexmojaki** [comment]
There's a separate setting `maxstring`.

As for how to display a specific variable completely, I would recommend `print`.

**Comment by cool-RR** [comment]
In your implementation, is there a way to accomplish the following? "Whenever `repr(x)` would be under 100 characters, display it in full without any truncation"

**Comment by alexmojaki** [comment]
No, there's no way to tell if e.g. a list is going to have a long repr without just computing the full thing.

**Comment by cool-RR** [comment]
I understand. I removed `reprlib` and switched back to `repr`. I don't want to sacrifice simple, common usecases for more esoteric ones.

@kagxin Please upgrade PySnooper. Now your string will display, assuming its representation is below 100 characters. If it's above 100 characters, you can monkeypatch PySnooper like this `pysnooper.utils.MAX_VARIABLE_LENGTH = 1000`

**Comment by alexmojaki** [comment]
Well you could still compute the full `repr` and switch to `reprlib` if it's too long. There are advantages besides performance.

> I don't want to sacrifice simple, common usecases for more esoteric ones.

Keep in mind that this issue was not such a use case, just a reminder that we should have set `maxstring` as well.

I don't know which use cases you have in mind, it's only under pretty specific circumstances that your implementation will display information the user wants that `reprlib` won't and that wouldn't be better obtained by other means.

**Comment by kagxin** [comment]
thanks
