### ISSUE TITLE
activate / desactivate pysnooper ?

### ISSUE THREAD

**Issue by yvonhubert** [cool-RR/PySnooper#127]
hello,

is it possible to activate / desactivate pysnooper in code ?

the goal is to keep pysnooper in production and activate it when a problem is occuring.

thanx

**Comment by cool-RR** [comment]
Right now, there isn't. This is a good feature, and if anyone volunteers to implement it, I'll give you some guidelines. Let me know if that's you. 

As a user, do you expect to enable/disable it with an environment variable, or did you have any other kind of interface in mind?

**Comment by yvonhubert** [comment]
perhaps you can implement the same schema used by the module logging :

logging.config.fileConfig('/washingmachine/src/resources/logging.properties')

**Comment by cool-RR** [comment]
Nah, I'm against a config file.

@alexmojaki what do you think would be a good interface for a user to toggle PySnooper? Environment variable or anything else?

**Comment by yvonhubert** [comment]
ok no problem .. so the best way for my case is an environment variable. We don't want to edit the python code when we investigate problems in prodcution

**Comment by alexmojaki** [comment]
In my version, configuration such as output is set globally by calling a separate function, instead of in each call to snoop. It includes an `enabled` parameter which the user sets directly. Something like that would be the most flexible (whether or not it can touch any other configuration). The user can easily check for an environment variable themselves.

An environment variable would be less flexible but would be the easiest interface and would work for most users. Its presence should probably disable pysnooper, so it's enabled by default.

You could also provide both interfaces, if you can decide which one should take precedence if both are used.

**Comment by cool-RR** [comment]
@alexmojaki Great, thanks for the input!

@yvonhubert If you or anyone else would like to implement, go ahead. The environment variable name should be `PYSNOOPER_DISABLED` and if it has a non-empty value, then PySnooper is in no-op mode, i.e. any decorated functions will just be the original functions and the context manager will not do anything. Tests should be added.

**Comment by pikez** [comment]
@cool-RR @yvonhubert   I'm interested in it.  If no one is doing this now, I will try to implement it in several days.

**Comment by cool-RR** [comment]
@pikez Great! If you'll have any questions, let me know. Otherwise I'll be happy to see the pull request when it's ready.

And if you'll be hungry for more features later, #1 would be good!
