### ISSUE TITLE
feature request: Support showing source code in exec

### ISSUE THREAD

**Issue by longqzh** [cool-RR/PySnooper#135]
Thanks for your awesome project!   It works with the code which run in the exec(), but it can't show the source code. I found that pysnooper try to get the source code from file. So Is it possible to show the source code in exec?

**Comment by alexmojaki** [comment]
If you just `exec(string)`, then in general that string cannot be recovered by anyone, which is why it also doesn't show up in tracebacks.

If you are in control of the code that does `exec(string)`, change it to `exec(compile(string, filename, 'exec'))` and put `string` in the file `filename`, and that will work.

**Comment by longqzh** [comment]
Thanks very much. It works properly :)
