### ISSUE TITLE
Compatibility with awsebcli

### ISSUE THREAD

**Issue by lodb** [cool-RR/PySnooper#19]
There are requirement incompatibilities with the `awsebcli` package from amazon. I'm not sure if this has an easy fix or pysnooper _really_ needs the specified versions of `future` and `six`:

`awsebcli 3.15.0 has requirement future<0.17.0,>=0.16.0, but you'll have future 0.17.1 which is incompatible.`
`awsebcli 3.15.0 has requirement six<1.12.0,>=1.11.0, but you'll have six 1.12.0 which is incompatible.`

**Comment by cool-RR** [comment]
I understand the problem. I don't think it's worthwhile to fix on PySnooper's end, because awsebcli is insisting on older versions, and other packages might insist on even older versions.

What you can do is install PySnooper manually by downloading and running `python setup.py install`. That'll likely work.
