### ISSUE TITLE
Dependencies on decorator and six

### ISSUE THREAD

**Issue by lleontop** [cool-RR/PySnooper#48]
Not much of an issue but just wondering if bundling external dependencies is just temporary or permanent? Isn't it kind of a bad practice to in-source external dependencies in terms of features/bug fixes/compatibility of these external modules and better come from PYPI directly?

**Comment by cool-RR** [comment]
It's kind of a bad practice, but:

1. It prevents all kinds of problems that happen because of poor packaging
infrastructure. Django made a similar choice in the past.
2. We have only 2 dependencies. We could even cut down on `six` if we
wanted, we only use a small portion of it.
3. We're not likely to need any updates on our 2 dependencies in the next 5
years. They are very mature modules.

**Comment by lleontop** [comment]
Still kind of sceptical about it since most mature modules have good packaging and as I could see Django now has install dependencies not bundled (pytz and sqlparse) and we might need to have more dependencies in the future (and we will need to add the dependency and the dependency dependencies code) but as I said it's ok not a real issue right now, we can revisit this if it is required.

**Comment by lleontop** [comment]
Also the travis error seems to be the order and the scope of imports to get the version. It seems that during install it needs to get the version and to do that it also imports pysnooper.py that needs decorator but pip hasn't installed any dependecies yet. I can have a look at it and possibly change the order and scope of imports if you think it would be beneficial

**Comment by cool-RR** [comment]
You could, but these problems happen and they'll continue to happen in different ways. I know it's a backwards kind of solution, but removing all dependencies lets me spend less time with these problems.

**Comment by bittner** [comment]
As I commented on commit 5c31dfc28c283b732296e6c09f64ce8e6d395687, `__init__.py` shouldn't do anything but define attributes. Problems with importing the package to install in `setup.py` are typically related to import issue (circular imports, import of dependencies not present or similar).

That's why importing your own package in `setup.py` tends to be discouraged in popular speech, but really this is never a problem unless you do dirty things in `__init__.py`. It just must be empty or almost empty. No logic that triggers the machinery.

**Comment by cool-RR** [comment]
I disagree, sorry.
